# Debian base required: PyTorch/ultralytics have no wheels on Alpine (musl).
# Supervisor requires build_from to match: registry/path/name:tag (full image reference).
build_from:
  amd64: docker.io/library/python:3.12-slim-bookworm
  aarch64: docker.io/library/python:3.12-slim-bookworm
